### ISSUE TITLE
auto_prefetch and the Admin site

### ISSUE THREAD

**Issue by YolCruz** [tolomea/django-auto-prefetch#177]
### Python Version

3.9.5

### Django Version

3.2.15

### Package Version

1.3.0

### Description

I have two models that inherit from another model with a Meta class in in, like this:

```python
from django.contrib.auth.models import User
from django.db import models

class Sport(models.Model):
    name = models.CharField(unique=True, null=False, max_length=32)
    description = models.TextField(blank=True)

class Preferences(models.Model.Meta):
    sport = models.ForeignKey(Sport, on_delete=models.PROTECT)
    user = models.OneToOneField(User, on_delete=models.PROTECT)

    class Meta:
        abstract = True

class ProviderPreferences(Preferences):
    biography = models.TextField(null=True, blank=True, default=None)
    performance_info = models.TextField(blank=True, null=True, default=None)
    products_to_offer = models.TextField(blank=True, null=True, default=None) 

    class Meta:
        abstract = False

class SubscriberPreferences(Preferences):
    favorites = models.TextField(blank=True, null=True, default=None)

    class Meta:
        abstract = False
```

I want to use auto_prefetch for these models. So I change the corresponding values like this:
```python
from django.contrib.auth.models import User
from django.db import models
import auto_prefetch

class Sport(auto_prefetch.Model):
    name = models.CharField(unique=True, null=False, max_length=32)
    description = models.TextField(blank=True)

class Preferences(auto_prefetch.Model.Meta):
    sport = auto_prefetch.ForeignKey(Sport, on_delete=models.PROTECT)
    user = auto_prefetch.OneToOneField(User, on_delete=models.PROTECT)

    class Meta:
        abstract = True

class ProviderPreferences(Preferences):
    biography = models.TextField(null=True, blank=True, default=None)
    performance_info = models.TextField(blank=True, null=True, default=None)
    products_to_offer = models.TextField(blank=True, null=True, default=None) 

    class Meta:
        abstract = False

class SubscriberPreferences(Preferences):
    favorites = models.TextField(blank=True, null=True, default=None)

    class Meta:
        abstract = False
```

I also want to allow changes to the models in the Django admin site. I have this in the `admin.py` file:

```python
from guardian.admin import GuardedModelAdmin
from accounts.models import SubscriberPreferences

@admin.register(SubscriberPreferences)
class SubscriberPreferenceAdmin(GuardedModelAdmin):
    list_display = ["user",]
    search_fields = ["user__username"]
    change_form_template = "admin/custom/change_form.html"
    readonly_fields = ("user",)
```

When I run `manage makemigrations` I get the following error

```shell
❯ manage makemigrations
Traceback (most recent call last):
  File "/home/yolcruz/dev/website/manage.py", line 32, in <module>
    main()
  File "/home/yolcruz/dev/website/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/yolcruz/.virtualenvs/myenv/lib/python3.9/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/home/yolcruz/.virtualenvs/myenv/lib/python3.9/site-packages/django/core/management/__init__.py", line 395, in execute
    django.setup()
  File "/home/yolcruz/.virtualenvs/myenv/lib/python3.9/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/yolcruz/.virtualenvs/myenv/lib/python3.9/site-packages/django/apps/registry.py", line 122, in populate
    app_config.ready()
  File "/home/yolcruz/.virtualenvs/myenv/lib/python3.9/site-packages/django/contrib/admin/apps.py", line 27, in ready
    self.module.autodiscover()
  File "/home/yolcruz/.virtualenvs/myenv/lib/python3.9/site-packages/django/contrib/admin/__init__.py", line 24, in autodiscover
    autodiscover_modules('admin', register_to=site)
  File "/home/yolcruz/.virtualenvs/myenv/lib/python3.9/site-packages/django/utils/module_loading.py", line 47, in autodiscover_modules
    import_module('%s.%s' % (app_config.name, module_to_search))
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/yolcruz/dev/website/accounts/admin.py", line 108, in <module>
    class SubscriberPreferenceAdmin(GuardedModelAdmin):
  File "/home/yolcruz/.virtualenvs/myenv/lib/python3.9/site-packages/django/contrib/admin/decorators.py", line 100, in _model_admin_wrapper
    admin_site.register(models, admin_class=admin_class)
  File "/home/yolcruz/.virtualenvs/myenv/lib/python3.9/site-packages/django/contrib/admin/sites.py", line 113, in register
    if model._meta.abstract:
AttributeError: type object 'SubscriberPreferences' has no attribute '_meta'
```

It seems like a problem with the `auto_prefetch.Model.Meta` class missing the attribute `_meta`. How can I solve this problem?

**Comment by adamchainz** [comment]
You had a problem with your model class here:

```python
class Preferences(auto_prefetch.Model.Meta):
    ...
```

`Preferences` is a model, so it should inherit from `auto_prefetch.Model`:

```python
class Preferences(auto_prefetch.Model):
    ...
```

Inheriting from the auto prefetch `Model.Meta` class leaves you with not a model class, whcih the admin then rightly fails to register.

Try that!

**Comment by YolCruz** [comment]
I tried that. I got the error

```shell
❯ manage makemigrations
SystemCheckError: System check identified some issues:

ERRORS:
accounts.PoviderPreferences: (auto_prefetch.E001) ProviderPreferences inherits from auto_prefetch.Model, but its Meta class does not inherit from auto_prefetch.Model.Meta
accounts.SubscriberPreferences: (auto_prefetch.E001) SubscriberPreferences inherits from auto_prefetch.Model, but its Meta class does not inherit from auto_prefetch.Model.Meta
```

It seems like the solution was to do

```python
class Preferences(auto_prefetch.Model):
    sport = auto_prefetch.ForeignKey(Sport, on_delete=models.PROTECT)
    user = auto_prefetch.OneToOneField(User, on_delete=models.PROTECT)

    class Meta(auto_prefetch.Model.Meta):
        abstract = True
```
